### ISSUE TITLE
现在使用其框架报错undifined is not a object，修改其源码后正常使用

### ISSUE THREAD

**Issue by VenusPP** [ryanyu104/react-native-city-select#1]
// 修改内容如下
// index.js
import PropTypes from 'prop-types';
CitySelect.propTypes = {
  header: PropTypes.bool,
  cancelText: PropTypes.string,
  cancelColor: PropTypes.string,
  cancelSize: PropTypes.number,
  titleText: PropTypes.string,
  cancelCity: PropTypes.func.isRequired,
  selectCity: PropTypes.func.isRequired,
  cityData: PropTypes.object.isRequired,
}

**Comment by ryanyu104** [comment]
谢谢，会在下个版本修复。
